### PR TITLE
clarify field names of web config form, fixes #18

### LINKED ISSUE #18: setup UI: clarify field names
The field names in the setup menu are all else than clear / self explaining:
```
Current         ---->      Suggested
Thing Name                 Built-in WiFi AccessPoint ESSID (do not change)
AP password                Built-in WiFi AccessPoint Password
WiFi SSID                  WiFi Client ESSID
WiFi passwort              WiFi Client Password
```

If named like that, I guess the docs could be shortened as it is self-explaining.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
note: did not change the "WiFi" wording (was there before, is there still).

### CODE REVIEW

**Comment by rexfue** [comment]
Please do not merge. Lets first ask the others. I guess, we must decide, if the UI shall be in english or in german.
BTW: "WiFi **client** SSID" sounds wrong for me:  this is not a client, this is my access points SSID.

**Comment by ThomasWaldmann** [comment]
I did not change the language in this PR, so that discussion is not relevant to the changes in this PR (besides that we may or may not want to change it later again).

The device has 2 functionalities we need to configure:
- a builtin wifi accesspoint (thus the phrasing "Geiger accesspoint")
- a builtin wifi client (thus the phrasing "wifi client")

Of course you need to configure the wifi client with the **same** ssid/password as your home/company/public accesspoint or the client won't be able to connect to the AP. But still, we are configuring the client here, not the accesspoint. Also, it would be totally confusing to talk of an AP for these last 2 fields as we also really have an AP configuration (first 2 fields).

**Comment by ThomasWaldmann** [comment]
What's really missing in this PR: the docs in the README.md need a corresponding update.

**Comment by ThomasWaldmann** [comment]
docs updated.

**Comment by ThomasWaldmann** [comment]
please merge this before any more recent PR that changes the readme to avoid merge conflicts.

**Comment by rexfue** [comment]
merged #75 
But I'am really not happy with the new names. They are as bad as the old ones. But because I want to redesign the GUI anyway, that doesn't bother me.

**Comment by ThomasWaldmann** [comment]
incremental improvements are still better than no improvement (or waiting long for the ultimate thing).

**Pull request merged**
