### PR TITLE
Language consistency

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
As discussed, let's have the source in English.

### CODE REVIEW

**Comment by rexfue** [comment]
I disagree on wert => cpm.
cpm is a unit. You never give a variable a unit name. Maybe you can call it 'tubecount_cpm' or something similar, but not only cpm.

**Comment by ThomasWaldmann** [comment]
You're right, it is a unit.

tubecount sounds strange, we're not counting tubes. :)

pulse_count?

radiation_cpm?

**Comment by rexfue** [comment]
radiation_cpm sounds good

**Comment by ThomasWaldmann** [comment]
Fixed.

**Comment by ThomasWaldmann** [comment]
btw, there are quite some other variables like cpm and current_cpm in the code.

**Comment by ThomasWaldmann** [comment]
OK, guess I am finished with language consistency for now. Merge?

**Comment by rexfue** [comment]
merged #28 into master

**Pull request merged**
