### PR TITLE
Use IotWebConf as a library

### LINKED ISSUE #143: duplication of IotWebConf into our codebase
Seems like we have a full copy of that.

Problems:
- the lib version is unknown (at least I could not find it anywhere)
- hard to update
- it is locally modified to add setThingName functionality

Maybe the modification could be done in a cleaner way by subclassing and extending that way?
If so, we could remove the lib code from git and just install it via arduino library manager, as usual.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
fixes #143

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
any comment?

i tried it, seems to work.

**Comment by rexfue** [comment]
Yes it work. But the problem with the hard coded names for Geiger-APi etc. remains, that you changed.
I have no idea, how to solve this; beside the same hack.

**Comment by ThomasWaldmann** [comment]
What do you mean precisely?

"problem with the hard coded names for Geiger-APi" ?

**Comment by rexfue** [comment]
This:
  this->_thingNameParameter = IotWebConfParameter("Geiger accesspoint SSID", "iwcThingName", this->_thingName, IOTWEBCONF_WORD_LEN);
  this->_apPasswordParameter = IotWebConfParameter("Geiger accesspoint password", "iwcApPassword", this->_apPassword, IOTWEBCONF_WORD_LEN, "password");
  this->_wifiSsidParameter = IotWebConfParameter("WiFi client SSID", "iwcWifiSsid", this->_wifiSsid, IOTWEBCONF_WORD_LEN);
  this->_wifiPasswordParameter = IotWebConfParameter("WiFi client password", "iwcWifiPassword", this->_wifiPassword, IOTWEBCONF_WORD_LEN, "password");

Its hard coded in IotWebConf.cpp.

**Comment by ThomasWaldmann** [comment]
oh crap, i did not remember that hack... - i'll have a look ...

but in general, a lib should be used as a lib. otherwise maintaining / updating is just too much pain.

**Comment by rexfue** [comment]
agreed!  Maybe we should write similar stuff by ourselves - but why reinvent the wheel?
The luftdaten people did it by themselves, so  may be  we can steel  steel some code :-)

**Comment by ThomasWaldmann** [comment]
https://github.com/prampec/IotWebConf/issues/98

**Comment by ThomasWaldmann** [comment]
@rexfue solved with the help of @prampec!

**Comment by ThomasWaldmann** [comment]
merge?

**Comment by rexfue** [comment]
OK

Von meinem iPad gesendet

**Pull request merged**
