### PR TITLE
Rename userdefines.h, fixes #15

### LINKED ISSUE #15: rename userdefines.h?
Problem:

The user has to edit `userdefines.h` to adapt to their hardware.

But it is a version controlled file, so these edits always show up in git status / git diff / etc. and get into the way when developing.

Suggestion:

Rename `userdefines.h -> userdefines-example.h` and add a comment in there:

```
// User / hardware specific definitions - do NOT edit THIS (example) file.
// To use them please copy this file to userdefines.h (do not add that file to version control)
// and then edit userdefines.h as appropriate for your use case / hardware.
```

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@rexfue @ecocurious ^^^

BTW, do you automatically get notified or does one need to mention you?

**Comment by rexfue** [comment]
I guess I will be notified - now. I clicked the ’subscribe’ button.

**Comment by ThomasWaldmann** [comment]
ping! :-)

can you merge soon please, so that I can continue working on stuff without causing merge conflicts?

**Comment by rexfue** [comment]
merged #15

**Pull request merged**
