### PR TITLE
fix indentation / spacing, remove tabs

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
no code changes.

trying to be at least "locally consistent".

trivial, please merge quickly.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
BTW, is there some commonly accepted style guide for C nowadays?

I'm coming from the Python world and there basically everybody agrees on PEP8 (mostly), like e.g. using 4 spaces to indent and never ever use tabs.

**Comment by ThomasWaldmann** [comment]
BTW, same here:

Maybe our editors can be configured to automatically expand tabs to (e.g.) 4 spaces on save, to avoid a mess of mixed spaces and tabs...

**Comment by rexfue** [comment]
merged
I don't know, if there is any standard, i guess, there are many! 
But i agree, 4 spaces is OK. And open brace on line of statement, not on extra line.

**Comment by rexfue** [comment]
Change my answer to '2 spaces'. That's what is in the file and we will keep this.

**Comment by ThomasWaldmann** [comment]
OK, so let's use 2. \o/

**Pull request merged**
